SET @userId='flast';
SET @email='flast@mdsol.com';
SET @firstName='First';
SET @lastName='Last';
SET @userPwd=UPPER(SHA1('pass1l0110l011lword'));
SET @uuid='71f7c88e-f00d-beaf-cafe-12313b07b551';    -- INNOVATE
-- SET @uuid='4e048fb4-feed-cafe-c0c0-12313928c767'; -- PROD

START TRANSACTION;

SELECT @resourceId:=id FROM resource_def WHERE uuid=@uuid;
SELECT @companyId:=id FROM company_def WHERE NAME='MDSOL';
SELECT @roleId:=id FROM role_def WHERE name='Admin';
SELECT @id:=current_id+1 FROM key_gen;

INSERT INTO resource_def(ID, USER_ID, USER_PWD, IDENTIFIER, UUID, SESSION_IDENT, SYSTEM_USER, LOGIN_ALLOWED, LOGGED_OUT, TYPE, AUTOMATED_USER, PASSWORD_EXPIRATION, PASSWORD_ENFORCEMENT, PASSWORD_LAST_CHANGE_DATE, PASSWORD_FORCE_CHANGE, SESSION_TIME_OUT_SECONDS, SECURITY_QUEST_1, SECURITY_ANS_1, SECURITY_QUEST_2, SECURITY_ANS_2, AUTHENTICATION_RULE, PREV_USER_PWD1, PREV_USER_PWD2, CONTACT_ID, FIRST_NAME, MID_NAME, LAST_NAME, NICK_NAME, LANG, EXTERNAL_ID, COMPANY_ID, DEPARTMENT_ID, LINE_MANAGER_ID, RESP_REGION, CURRENT_ROLE_ID, LOGIN_ATTEMPTS, DIVISION, DIVISION_ID, TITLE, QUALIFICATION, JOB_TITLE, REMOTE_USER, REMOTE_SYNCH_POLICY, SECURITY_LEVEL, SECURITY_ACCESS, SAGE_SUPPLIER_CODE, ACCOUNTING_CODE, EMPLOY_STATUS, FLEXI_TIME, ALERT_ACK, HIRE_DATE, BIRTH_DATE, TIMESHEET_LOCK_DATE, EXPENSE_LOCK_DATE, TEL_NO, ALT_TEL_NO, MOBILE_NO, FAX_NO, PAGER_NO, EMAIL, EMAIL_ADDRESS, CURRENCY, TIME_ZONE, LOCALE, INTERNAL_COST, BILL_RATE, OVERTIME_BILL_RATE, HOLIDAY_ENTITLEMENT, HE_LEAVE_PERIOD, BEREAVEMENT_ENTITLEMENT, BE_LEAVE_PERIOD, MATERNITY_ENTITLEMENT, ME_LEAVE_PERIOD, PRODUCTIVE_HOURS, PRODUCTIVE_PERIOD, MAX_BILL_HOURS, MAX_BILL_HRS_PERIOD, MAX_OVERTIME_HOURS, MAX_OVERTIME_HRS_PERIOD, TERMINATION_DATE, DISTANCE_CURRENCY, DISTANCE_UNIT, DISTANCE_RATE, NOTES, LAST_UPDT_BY_ID, CREATED_BY_ID, ACTIVE, ARCHIVE_FLAG, DEL_FLAG, CREATE_DATE, USER_TIME_ZONE, TZ_ID, UPDATE_DATE, AUTO_UPDATE_DATE, AUTO_UPDATE_SRC)
SELECT @id, @userId, @userPwd, NULL,@uuid, NULL, 'Y', 'Y', 'N', '1', 'N', '0', '0', NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'DUMMY', 'DUMMY', NULL, @firstName, NULL, @lastName, NULL, 'en-US', NULL, @companyId, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'server', 0, 0, NULL, NULL, 'FULL_TIME', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @email, NULL, 'USD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'WEEKLY', NULL, 'WEEKLY', NULL, 'WEEKLY', NULL, 'Kms', 'Kms', NULL, NULL, NULL, NULL, 'Y', 'N', 'N', CURRENT_TIMESTAMP, '0', NULL, NULL, NULL, NULL
FROM resource_def r WHERE @resourceId IS NULL
LIMIT 1;

UPDATE key_gen SET current_id=current_id+1 WHERE @resourceId IS NULL; 
SET @resourceId=COALESCE(@resourceId, @id);

SELECT @resourceRoleId:=id FROM resource_role WHERE role_id=@roleId AND RESOURCE_ID=@resourceId;
SELECT @id:=current_id+1 FROM key_gen;

INSERT INTO resource_role(ID, ROLE_ID, RESOURCE_ID, PRIMARY_FLAG, DEFAULT_ROLE, GLOBAL_ROLE, MENU_LEVEL, DEFAULT_SRVC, READ_ONLY, DEL_PERM, INS_PERM, UPD_PERM, LAST_UPDT_BY_ID, CREATED_BY_ID, ACTIVE, ARCHIVE_FLAG, DEL_FLAG, CREATE_DATE, USER_TIME_ZONE, TZ_ID, UPDATE_DATE, AUTO_UPDATE_DATE, AUTO_UPDATE_SRC)
SELECT @id, @roleId, @resourceId, NULL, 'Y', 'N', 0, NULL, 'N', 'N', 'Y', 'Y', NULL, NULL, 'Y', 'N', 'N', CURRENT_TIMESTAMP, '0', NULL, NULL, NULL, NULL
FROM resource_role r WHERE @resourceRoleId IS NULL
LIMIT 1;

UPDATE key_gen SET current_id=current_id+1 WHERE @resourceRoleId IS NULL; 

COMMIT;