SELECT scp.ID AS CRF_PAGE_ID
  , scp.IDENTIFIER AS CRF_PAGE_IDENTIFIER
  , scp.UUID AS CRF_PAGE_UUID
  , scp.NAME AS CRF_PAGE_NAME
  , scp.REFERENCE AS CRF_PAGE_REFERENCE
  , scp.VERIFIED AS CRF_PAGE_VERIFIED
  , il.ID AS INTEGRATION_LOG_ID
  , h.CREATE_DATE
  , il.NAME AS IMPORTER
  , il.CREATE_DATE AS IMPORT_START_TIME
  , il.UPDATE_DATE AS IMPORT_END_TIME
  , LEFT(il.TGT_FILE_NAME, LOCATE('/', il.TGT_FILE_NAME)-1) TGT_PATH
  , SUBSTRING(il.TGT_FILE_NAME, LOCATE('/', il.TGT_FILE_NAME)+1) TGT_FILE
  , il.COMMENTS
  , il.DETAIL
FROM 
  (SELECT *
FROM history h
WHERE h.notes LIKE 'update subject_crf_page set VERIFIED=''Y''%LAST_UPDT_BY_ID=null%') h
  LEFT JOIN 
    (SELECT ID
    , NAME
    , COMMENTS
    , DETAIL
    , CREATE_DATE
    , UPDATE_DATE
    , SUBSTRING(TGT_FILE_NAME, LOCATE('releases/', TGT_FILE_NAME)+LENGTH('releases/0123456789012345678901234567890123456789/app/WEB-INF/../../glue//')) TGT_FILE_NAME
   FROM integration_log) il ON h.CREATE_DATE BETWEEN il.CREATE_DATE AND il.UPDATE_DATE
  INNER JOIN subject_crf_page scp ON scp.ID=h.ROW_ID
